server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - AddRequestHeader=X-Internal-Secret, gateway-approved
        - AddRequestHeader=X-Trace-Id, ${random.uuid}
        - name: Retry
          args:
            retries: 2
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            methods: GET, POST, PUT
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/user/**,/api/bookings/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**,/api/rooms/**
          filters:
            - RemoveRequestHeader=Cookie
            - PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.143
